# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=20)),
                ('coarse', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=20)),
            ],
        ),
    ]
